service: GolangCognitoSample

provider:
  name: aws
  runtime: go1.x
  timeout: 10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1

custom:
  defaultStage: develop
  otherfile:
package:
  include:
    - ./bin/main

functions:
  exec:
    handler: bin/main
    description: Cognitoの特定のUserPoolに紐づくユーザー情報一覧を取得する
